# Generated by Django 5.0.6 on 2024-06-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_remove_post_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='maintemplate_images/defaultpost.png', null=True, upload_to='images'),
        ),
    ]
