# Generated by Django 5.0.6 on 2024-06-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_alter_post_thumbnail_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
