# Generated by Django 5.0.6 on 2024-06-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
